version: "2"

linters:
  enable:
    - bodyclose
    - errorlint
    - gocritic
    - gosec
    - misspell
    - noctx
    - revive
    - unconvert
    - unparam
  exclusions:
    rules:
      - path: _test\.go
        linters: [gosec, noctx, unparam]
